name: Run notebooks

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run notebooks with tox
        run: tox -e notebooks
