name: Run notebooks

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC
  # Allow job to be triggered manually from GitHub interface
  workflow_dispatch:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download data file from G-Node GIN
        run: |
          DATA_PATH="${{ env.TEST_DATA_HOME || github.workspace }}/nifreeze-tests"
          mkdir -p "$DATA_PATH"
          curl -L -o "${DATA_PATH}/hcpdata.npz" https://gin.g-node.org/nipreps-data/tests-nifreeze/src/master/hcpdata.npz
          echo "TEST_DATA_HOME"
          ls -la ${{ env.TEST_DATA_HOME }}
          echo "workspace"
          ls -la ${{ github.workspace }}
          echo "nifreeze-tests"
          ls -la ${{ github.workspace }}/nifreeze-tests

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt install texlive texlive-latex-extra texlive-fonts-recommended cm-super dvipng

      - name: Install git-annex
        run: |
          sudo apt-get update
          sudo apt-get install -y git-annex

      - name: Configure Git user for DataLad
        run: |
          git config --global user.email "nipreps@gmail.com"
          git config --global user.name "nipreps-bot"

      - name: Install DataLad
        run: pip install datalad

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Download data from OpenNeuro
        run: |
          DATA_PATH="${{ env.TEST_DATA_HOME || github.workspace }}/nifreeze-tests"
          mkdir -p "$DATA_PATH"
          bash scripts/fetch_fmri_nb_openneuro_data.sh "$DATA_PATH"

      - name: Run notebooks with tox
        run: tox -e notebooks
