name: Run notebooks

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC
  # Allow job to be triggered manually from GitHub interface
  workflow_dispatch:

defaults:
  run:
    shell: bash

# Force tox and pytest to use color
env:
  FORCE_COLOR: true
  TEST_DATA_HOME: /home/runner/nifreeze-tests/
  NIFREEZE_WERRORS: 1
  TEST_DATA_REPO: https://gin.g-node.org/nipreps-data/tests-nifreeze

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-notebooks:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt install texlive texlive-latex-extra texlive-fonts-recommended cm-super dvipng

      - name: Install git-annex
        run: |
          sudo apt-get update
          sudo apt-get install -y git-annex

      - name: Configure Git user for DataLad
        run: |
          git config --global user.email "nipreps@gmail.com"
          git config --global user.name "nipreps-bot"

      - name: Install DataLad
        run: pip install datalad

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Download data from OpenNeuro
        run: |
          ${{ github.workspace }}/scripts/fetch_fmri_nb_openneuro_data.sh "${TEST_DATA_HOME}"

      - name: Run notebooks with tox
        run: tox -e notebooks
